let a=5;
let b=a++;
console.log(a);
console.log(b);
let c=5;
let d=c++ + ++c +c;
console.log(c);
console.log(d);
console.log("7" * "2");
console.log("7a" * 2);
console.log(3/0);
console.log(0.1+0.2);
console.log(0.2-0.7);
console.log("7" * undefined);
console.log([1,2] + [3,2]);
console.log([1,2] * [3,2]);
console.log("2">"12");
console.log("2">12);
console.log(0.1+0.9 == true);
console.log(0.1>null);
console.log(0.1>undefined);
console.log(0==null);
console.log(undefined==null);
console.log(false==null);
console.log(false<null);
console.log("100"==10*10);
console.log("1"==true);
console.log("25"<"125");
console.log("0"==false);
console.log(false==undefined);
console.log(null==undefined);
console.log(true<5);
console.log(null<-5);